In [1]:
import numpy as np

In [2]:
np 

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a= np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [8]:
a[3] = 4

In [9]:
a

array([ 1,  2,  3,  4,  7, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n=np.array([[1,2,3],[4,5,6], [7,8,9]])

In [17]:
n[0,1]

np.int64(2)

In [18]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n[0]

array([1, 2, 3])

In [20]:
n[2]=[11,12,13]

In [21]:
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13]])

In [22]:
n[:,1]

array([ 2,  5, 12])

In [23]:
n[:,2] = [14,15,16]

In [24]:
n

array([[ 1,  2, 14],
       [ 4,  5, 15],
       [11, 12, 16]])

In [29]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [30]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [32]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a +1

array([1, 2, 3, 4, 5])

In [35]:
a*2

array([0, 2, 4, 6, 8])

In [37]:
b = (10 + (a*2))**2/100

In [38]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [39]:
c = a+b
c

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [40]:
a >= 2

array([False, False,  True,  True,  True])

In [41]:
a>b

array([False, False,  True,  True,  True])

In [42]:
a[ a >b]

array([2, 3, 4])

In [43]:
a.min()

np.int64(0)

In [44]:
a.max()

np.int64(4)

In [45]:
a.sum()

np.int64(10)

In [46]:
a.mean()

np.float64(2.0)

In [47]:
a.std()

np.float64(1.4142135623730951)