In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [3]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
u * 2

array([ 4,  8, 10, 12])

In [ ]:
Vector * Vector (Dot Product)

In [7]:
def vector_vector_multiplication (u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result +u[i] * v[i]
    return result

In [8]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [ ]:
Numpy Formula

In [9]:
u.dot(v)

np.int64(14)

In [ ]:
Matrix- Vector Multiplication

In [10]:
U = np.array([[2,4,5,6],
             [1,2,1,2],
             [3,1,2,1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [12]:
def matrix_vector_multiplication (U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
        
    return result

In [13]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [ ]:
Numpy Formula

In [14]:
U.dot(v)

array([14,  5,  5])

In [ ]:
Matrix - Matrix Multiplication 

In [27]:
V = np.array([[1, 1, 2],
     [0, 0.5, 1],
     [0, 2, 1],
     [2, 1, 0],
     ])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_columns = V.shape[1]

    result = np.zeros((num_rows, num_columns))

    for i in range(num_columns):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:,i] = Uvi
    return result

In [29]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
Numpy Formula

In [30]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
Identity Matrix 

In [31]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
I = np.eye(3)

In [33]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [34]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
Inverse

In [36]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [40]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [41]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])